name: merge group

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]
    
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - uses: raven-actions/debug@v1
      - run: echo ${{ secrets.FLAG }}
