name: Chall 1
on:
  issues:
    types:
      - opened
      - edited
  pull_request_target:
  
permissions: 
  contents: read

jobs:
  a:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: raven-actions/debug@v1
      - run: echo ${{ github.event.pull_request.user.email }}
